services:
  attendance-module:
    build: .
    image: attendance-module:${IMAGE_TAG:-latest}
    container_name: attendance-module
    restart: unless-stopped
    environment:
      SUPABASE_AUTH_URL: http://192.168.2.100:8777
      SUPABASE_REST_URL: http://192.168.2.100:8779
      GOTRUE_URL: http://192.168.2.100:8777
      JWT_SECRET: ${JWT_SECRET}
      DEFAULT_INITIAL_PASSWORD: ${DEFAULT_INITIAL_PASSWORD}
    ports:
      - "8767:80"
